GET http://localhost:5000/users

###

GET http://localhost:5000/users/1

###

POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Evelyn Tucni",
  "email": "evelyn@yahoo.com",
  "password": "petdog123#"
}

###

PATCH http://localhost:5000/users/1
Content-Type: application/json

{
  "name": "Maverick",
  "email": "gruyere@gmail.com",
  "password": "blahblahblah#"
}

###

DELETE http://localhost:5000/users/6
Content-Type: application/json

### quiz stuff

GET http://localhost:5000/api/groups

###

GET http://localhost:5000/api/groups/1

###

PUT http://localhost:5000/api/groups/7
Content-Type: application/json

{
  "name": "Uses of Like",
  "level": 1,
  "description": "This activity helps you practise using like in different sentences.",
  "duration": "0-5 mins",
  "imageUrl": "/explore1.png"
}

###

DELETE http://localhost:5000/api/groups/6
Content-Type: application/json

###

POST http://localhost:5000/api/groups
Content-Type: application/json

{
  "name": "Prepositions used with adjectives",
  "level": 1,
  "description": "Find the correct preposition used with common adjectives.",
  "duration": "0-5 mins",
  "imageUrl": "/explore1.png"
}

###
GET http://localhost:5000/api/questions/?groupId=1
###

POST http://localhost:5000/api/questions
Content-Type: application/json

[{
  "question": "How do you say 'Apa kabar?' in English?",
  "groupId": 1
},
{
  "question": "How do you say 'Saya suka bermain futsal?' in English?",
  "groupId": 1
},
{
  "question": "What is an adjective you can use to describe a basketball?",
  "groupId": 1
},
{
  "question": "Which word is an example of simple continouous?",
  "groupId": 1
}]

###

GET http://localhost:5000/api/answers/?questionId=2

###

POST http://localhost:5000/api/answers
Content-Type: application/json

[
  {
    "questionId": 4,
    "name": "I am baking cookies.",
    "true": true
  },
  {
    "questionId": 4,
    "name": "I eat chicken.",
    "true": false
  },
  {
    "questionId": 4,
    "name": "I am cook rice.",
    "true": false
  },
  {
    "questionId": 4,
    "name": "I make applications.",
    "true": false
  }
]

###

GET http://localhost:5000/api/completions/1